name: mollie_flutter
description: Implement the Mollie checkout process easily into your Flutter app
version: 1.1.6
homepage: https://github.com/gauravmehta13/mollie_flutter
repository: https://github.com/gauravmehta13/mollie_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1


flutter_gen:
  line_length: 120

flutter:
  plugin:
    platforms:
        android:
            package: com.plugon.mollie
            pluginClass: MolliePlugin
        ios:
            pluginClass: MolliePlugin


  # To add assets to your plugin package, add an assets section, like this:
  # https://50north.de/kostenlose-payment-icons-fuer-den-europaeischen-markt/
  assets:
    - assets/icons/mastercard.png
    - assets/icons/klarna-sofort.png
    - assets/icons/paypal.png
    - assets/icons/klarna-rechnung-alt.png
    - assets/icons/sepa.png
    - assets/icons/ideal.png
    - assets/icons/applepay.png
    - assets/icons/bancontact.png
    - assets/icons/credit_card.png
    - assets/icons/belfius_pay.png
    - assets/icons/giropay.png
    - assets/icons/ideal.png
    - assets/icons/kbc.png
    - assets/icons/sofort.png
